runtime: python39  # Use the appropriate Python version
entrypoint: gunicorn -b :$PORT myproject.wsgi

instance_class: F2  # Adjust instance type as needed

env_variables:
  DJANGO_SETTINGS_MODULE: "myproject.settings"
  SECRET_KEY: "your-secret-key"
  DEBUG: "False"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

