# Generated by Django 5.1.6 on 2025-03-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('appreciation', 'Appreciation'), ('other', 'Other')], max_length=20),
        ),
    ]
