# Generated by Django 5.1.6 on 2025-03-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0012_alter_feedback_email_alter_feedback_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='type',
            new_name='feedback_type',
        ),
    ]
