# Generated by Django 5.1.6 on 2025-03-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0013_rename_type_feedback_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
