# Generated by Django 5.1.6 on 2025-03-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0014_alter_feedback_feedback_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
