# Generated by Django 5.1.6 on 2025-04-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0015_alter_feedback_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
